"""add unique constraint service period_start

Revision ID: 4e081a077cb9
Revises: 2947bbdd94c7
Create Date: 2026-06-15 10:11:34.249528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e081a077cb9'
down_revision: Union[str, None] = '2947bbdd94c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_service_period_start', 'cost_records', ['service', 'period_start'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_service_period_start', 'cost_records', type_='unique')
    # ### end Alembic commands ###
